###############################################################
#  Generated by:      Cadence Encounter 09.11-s084_1
#  OS:                Linux x86_64(Host ID 5013-w38)
#  Generated on:      Mon Mar 20 12:16:20 2017
#  Command:           saveIoFile -byOrder Scripts/sorter_top.save.io
###############################################################

(globals
    version = 3
    io_order = clockwise
)
(iopad
    (top
    (inst  name="vdd1"      place_status=placed     cell="PVDDDGZ")
	(inst  name="inpA_3"	place_status=placed )
	(inst  name="inpA_2"	place_status=placed )
	(inst  name="inpA_1"	place_status=placed )
	(inst  name="inpA_0"	place_status=placed )
	(inst  name="inpB_3"	place_status=placed )
	(inst  name="inpB_2"	place_status=placed )
	(inst  name="inpB_1"	place_status=placed )
	(inst  name="inpB_0"	place_status=placed )
    (inst  name="inpA_3_0"	place_status=placed )
	(inst  name="inpA_2_0"	place_status=placed )
	(inst  name="inpA_1_0"	place_status=placed )
	(inst  name="inpA_0_0"	place_status=placed )
	(inst  name="inpB_3_0"	place_status=placed )
	(inst  name="inpB_2_0"	place_status=placed )
	(inst  name="inpB_1_0"	place_status=placed )
	(inst  name="inpB_0_0"	place_status=placed )
    )

    (left
    (inst  name="padClkG"	place_status=placed )
    )

    (topleft
    (inst  name="c1"        place_status=placed cell="PCORNER")
    )

    (topright
    (inst  name="c2"        place_status=placed cell="PCORNER")
    )

    (bottom
	(inst  name="opRes_3"	place_status=placed )
	(inst  name="opRes_2"	place_status=placed )
	(inst  name="opRes_1"	place_status=placed )
	(inst  name="opRes_0"	place_status=placed )
	(inst  name="opRes_3_0"	place_status=placed )
	(inst  name="opRes_2_0"	place_status=placed )
	(inst  name="opRes_1_0"	place_status=placed )
	(inst  name="opRes_0_0"	place_status=placed )
    (inst  name="opRes_3_1"	place_status=placed )
	(inst  name="opRes_2_1"	place_status=placed )
	(inst  name="opRes_1_1"	place_status=placed )
	(inst  name="opRes_0_1"	place_status=placed )
	(inst  name="opRes_3_2"	place_status=placed )
	(inst  name="opRes_2_2"	place_status=placed )
	(inst  name="opRes_1_2"	place_status=placed )
	(inst  name="opRes_0_2"	place_status=placed )
    (inst  name="vss1"      place_status=placed cell="PVSSDGZ")
    )

    (bottomright
    (inst  name="c3"        place_status=placed cell="PCORNER")
    )

    (bottomleft
    (inst  name="c4"        place_status=placed cell="PCORNER")
    )
       
    (right
    (inst  name="vdd2"      place_status=placed     cell="PVDDDGZ")
    )
)
