###############################################################
#  Generated by:      Cadence Encounter 09.11-s084_1
#  OS:                Linux x86_64(Host ID 5013-w38)
#  Generated on:      Mon Mar 20 12:21:38 2017
#  Command:           floorPlan -site CORE -r 0.058823 0.7 20 20 20 20
###############################################################

Version: 8

Head Box: -405.0000 0.0000 1725.0000 1410.0000
IO Box: 300.0000 300.0000 1020.0000 1110.0000
Core Box: 300.3000 300.3000 1020.0000 1108.1400
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.660000
Row SpacingType = 1
Row Flip = 2
Core Row Site: CORE 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_101 CORE 300.3000 1100.2200 N 1090 1 0.6600 0.0000
DefRow: ROW_100 CORE 300.3000 1092.3000 FS 1090 1 0.6600 0.0000
DefRow: ROW_99 CORE 300.3000 1084.3800 N 1090 1 0.6600 0.0000
DefRow: ROW_98 CORE 300.3000 1076.4600 FS 1090 1 0.6600 0.0000
DefRow: ROW_97 CORE 300.3000 1068.5400 N 1090 1 0.6600 0.0000
DefRow: ROW_96 CORE 300.3000 1060.6200 FS 1090 1 0.6600 0.0000
DefRow: ROW_95 CORE 300.3000 1052.7000 N 1090 1 0.6600 0.0000
DefRow: ROW_94 CORE 300.3000 1044.7800 FS 1090 1 0.6600 0.0000
DefRow: ROW_93 CORE 300.3000 1036.8600 N 1090 1 0.6600 0.0000
DefRow: ROW_92 CORE 300.3000 1028.9400 FS 1090 1 0.6600 0.0000
DefRow: ROW_91 CORE 300.3000 1021.0200 N 1090 1 0.6600 0.0000
DefRow: ROW_90 CORE 300.3000 1013.1000 FS 1090 1 0.6600 0.0000
DefRow: ROW_89 CORE 300.3000 1005.1800 N 1090 1 0.6600 0.0000
DefRow: ROW_88 CORE 300.3000 997.2600 FS 1090 1 0.6600 0.0000
DefRow: ROW_87 CORE 300.3000 989.3400 N 1090 1 0.6600 0.0000
DefRow: ROW_86 CORE 300.3000 981.4200 FS 1090 1 0.6600 0.0000
DefRow: ROW_85 CORE 300.3000 973.5000 N 1090 1 0.6600 0.0000
DefRow: ROW_84 CORE 300.3000 965.5800 FS 1090 1 0.6600 0.0000
DefRow: ROW_83 CORE 300.3000 957.6600 N 1090 1 0.6600 0.0000
DefRow: ROW_82 CORE 300.3000 949.7400 FS 1090 1 0.6600 0.0000
DefRow: ROW_81 CORE 300.3000 941.8200 N 1090 1 0.6600 0.0000
DefRow: ROW_80 CORE 300.3000 933.9000 FS 1090 1 0.6600 0.0000
DefRow: ROW_79 CORE 300.3000 925.9800 N 1090 1 0.6600 0.0000
DefRow: ROW_78 CORE 300.3000 918.0600 FS 1090 1 0.6600 0.0000
DefRow: ROW_77 CORE 300.3000 910.1400 N 1090 1 0.6600 0.0000
DefRow: ROW_76 CORE 300.3000 902.2200 FS 1090 1 0.6600 0.0000
DefRow: ROW_75 CORE 300.3000 894.3000 N 1090 1 0.6600 0.0000
DefRow: ROW_74 CORE 300.3000 886.3800 FS 1090 1 0.6600 0.0000
DefRow: ROW_73 CORE 300.3000 878.4600 N 1090 1 0.6600 0.0000
DefRow: ROW_72 CORE 300.3000 870.5400 FS 1090 1 0.6600 0.0000
DefRow: ROW_71 CORE 300.3000 862.6200 N 1090 1 0.6600 0.0000
DefRow: ROW_70 CORE 300.3000 854.7000 FS 1090 1 0.6600 0.0000
DefRow: ROW_69 CORE 300.3000 846.7800 N 1090 1 0.6600 0.0000
DefRow: ROW_68 CORE 300.3000 838.8600 FS 1090 1 0.6600 0.0000
DefRow: ROW_67 CORE 300.3000 830.9400 N 1090 1 0.6600 0.0000
DefRow: ROW_66 CORE 300.3000 823.0200 FS 1090 1 0.6600 0.0000
DefRow: ROW_65 CORE 300.3000 815.1000 N 1090 1 0.6600 0.0000
DefRow: ROW_64 CORE 300.3000 807.1800 FS 1090 1 0.6600 0.0000
DefRow: ROW_63 CORE 300.3000 799.2600 N 1090 1 0.6600 0.0000
DefRow: ROW_62 CORE 300.3000 791.3400 FS 1090 1 0.6600 0.0000
DefRow: ROW_61 CORE 300.3000 783.4200 N 1090 1 0.6600 0.0000
DefRow: ROW_60 CORE 300.3000 775.5000 FS 1090 1 0.6600 0.0000
DefRow: ROW_59 CORE 300.3000 767.5800 N 1090 1 0.6600 0.0000
DefRow: ROW_58 CORE 300.3000 759.6600 FS 1090 1 0.6600 0.0000
DefRow: ROW_57 CORE 300.3000 751.7400 N 1090 1 0.6600 0.0000
DefRow: ROW_56 CORE 300.3000 743.8200 FS 1090 1 0.6600 0.0000
DefRow: ROW_55 CORE 300.3000 735.9000 N 1090 1 0.6600 0.0000
DefRow: ROW_54 CORE 300.3000 727.9800 FS 1090 1 0.6600 0.0000
DefRow: ROW_53 CORE 300.3000 720.0600 N 1090 1 0.6600 0.0000
DefRow: ROW_52 CORE 300.3000 712.1400 FS 1090 1 0.6600 0.0000
DefRow: ROW_51 CORE 300.3000 704.2200 N 1090 1 0.6600 0.0000
DefRow: ROW_50 CORE 300.3000 696.3000 FS 1090 1 0.6600 0.0000
DefRow: ROW_49 CORE 300.3000 688.3800 N 1090 1 0.6600 0.0000
DefRow: ROW_48 CORE 300.3000 680.4600 FS 1090 1 0.6600 0.0000
DefRow: ROW_47 CORE 300.3000 672.5400 N 1090 1 0.6600 0.0000
DefRow: ROW_46 CORE 300.3000 664.6200 FS 1090 1 0.6600 0.0000
DefRow: ROW_45 CORE 300.3000 656.7000 N 1090 1 0.6600 0.0000
DefRow: ROW_44 CORE 300.3000 648.7800 FS 1090 1 0.6600 0.0000
DefRow: ROW_43 CORE 300.3000 640.8600 N 1090 1 0.6600 0.0000
DefRow: ROW_42 CORE 300.3000 632.9400 FS 1090 1 0.6600 0.0000
DefRow: ROW_41 CORE 300.3000 625.0200 N 1090 1 0.6600 0.0000
DefRow: ROW_40 CORE 300.3000 617.1000 FS 1090 1 0.6600 0.0000
DefRow: ROW_39 CORE 300.3000 609.1800 N 1090 1 0.6600 0.0000
DefRow: ROW_38 CORE 300.3000 601.2600 FS 1090 1 0.6600 0.0000
DefRow: ROW_37 CORE 300.3000 593.3400 N 1090 1 0.6600 0.0000
DefRow: ROW_36 CORE 300.3000 585.4200 FS 1090 1 0.6600 0.0000
DefRow: ROW_35 CORE 300.3000 577.5000 N 1090 1 0.6600 0.0000
DefRow: ROW_34 CORE 300.3000 569.5800 FS 1090 1 0.6600 0.0000
DefRow: ROW_33 CORE 300.3000 561.6600 N 1090 1 0.6600 0.0000
DefRow: ROW_32 CORE 300.3000 553.7400 FS 1090 1 0.6600 0.0000
DefRow: ROW_31 CORE 300.3000 545.8200 N 1090 1 0.6600 0.0000
DefRow: ROW_30 CORE 300.3000 537.9000 FS 1090 1 0.6600 0.0000
DefRow: ROW_29 CORE 300.3000 529.9800 N 1090 1 0.6600 0.0000
DefRow: ROW_28 CORE 300.3000 522.0600 FS 1090 1 0.6600 0.0000
DefRow: ROW_27 CORE 300.3000 514.1400 N 1090 1 0.6600 0.0000
DefRow: ROW_26 CORE 300.3000 506.2200 FS 1090 1 0.6600 0.0000
DefRow: ROW_25 CORE 300.3000 498.3000 N 1090 1 0.6600 0.0000
DefRow: ROW_24 CORE 300.3000 490.3800 FS 1090 1 0.6600 0.0000
DefRow: ROW_23 CORE 300.3000 482.4600 N 1090 1 0.6600 0.0000
DefRow: ROW_22 CORE 300.3000 474.5400 FS 1090 1 0.6600 0.0000
DefRow: ROW_21 CORE 300.3000 466.6200 N 1090 1 0.6600 0.0000
DefRow: ROW_20 CORE 300.3000 458.7000 FS 1090 1 0.6600 0.0000
DefRow: ROW_19 CORE 300.3000 450.7800 N 1090 1 0.6600 0.0000
DefRow: ROW_18 CORE 300.3000 442.8600 FS 1090 1 0.6600 0.0000
DefRow: ROW_17 CORE 300.3000 434.9400 N 1090 1 0.6600 0.0000
DefRow: ROW_16 CORE 300.3000 427.0200 FS 1090 1 0.6600 0.0000
DefRow: ROW_15 CORE 300.3000 419.1000 N 1090 1 0.6600 0.0000
DefRow: ROW_14 CORE 300.3000 411.1800 FS 1090 1 0.6600 0.0000
DefRow: ROW_13 CORE 300.3000 403.2600 N 1090 1 0.6600 0.0000
DefRow: ROW_12 CORE 300.3000 395.3400 FS 1090 1 0.6600 0.0000
DefRow: ROW_11 CORE 300.3000 387.4200 N 1090 1 0.6600 0.0000
DefRow: ROW_10 CORE 300.3000 379.5000 FS 1090 1 0.6600 0.0000
DefRow: ROW_9 CORE 300.3000 371.5800 N 1090 1 0.6600 0.0000
DefRow: ROW_8 CORE 300.3000 363.6600 FS 1090 1 0.6600 0.0000
DefRow: ROW_7 CORE 300.3000 355.7400 N 1090 1 0.6600 0.0000
DefRow: ROW_6 CORE 300.3000 347.8200 FS 1090 1 0.6600 0.0000
DefRow: ROW_5 CORE 300.3000 339.9000 N 1090 1 0.6600 0.0000
DefRow: ROW_4 CORE 300.3000 331.9800 FS 1090 1 0.6600 0.0000
DefRow: ROW_3 CORE 300.3000 324.0600 N 1090 1 0.6600 0.0000
DefRow: ROW_2 CORE 300.3000 316.1400 FS 1090 1 0.6600 0.0000
DefRow: ROW_1 CORE 300.3000 308.2200 N 1090 1 0.6600 0.0000
DefRow: ROW_0 CORE 300.3000 300.3000 FS 1090 1 0.6600 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: Y 0.3300 2136 0.6600 1 6
Track: X -404.2500 3227 0.6600 1 6
Track: X -404.2500 3227 0.6600 1 5
Track: Y 0.3300 2136 0.6600 1 5
Track: Y 0.3300 2136 0.6600 1 4
Track: X -404.2500 3227 0.6600 1 4
Track: X -404.2500 3227 0.6600 1 3
Track: Y 0.3300 2136 0.6600 1 3
Track: Y 0.3300 2136 0.6600 1 2
Track: X -404.2500 3227 0.6600 1 2
Track: X -404.2500 3227 0.6600 1 1
Track: Y 0.3300 2136 0.6600 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 1720.9500 2 4.0500
GCellGrid: X -404.2500 323 6.6000
GCellGrid: X -405.0000 2 0.7500
GCellGrid: Y 1406.1300 2 3.8700
GCellGrid: Y 0.3300 214 6.6000
GCellGrid: Y 0.0000 2 0.3300

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: POWR -pwr
PhysicalNet: GRND -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val isAltLayer=val isPffGroup=val > #
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval coreToBottom=fval   #
#         pinSpacingNorth=val pinSpacingWest=val pinSpacingSouth=val      #
#         pinSpacingEast=val  blockedLayers=xval >       #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name"                    #
#                       pins=nr spacing=val isOptOrder=1 isAltLayer=1 >   #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num cell="name" >                       #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <Partition name="sorter_top" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=2 pinSpacingWest=2 pinSpacingSouth=2 pinSpacingEast=2 blockedLayers=0x3f >
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes />
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x3

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .sorter_top13928.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: c2 PCORNER 1425.0000 1110.0000 NE R180 - 00
IO: inpB_0_0 PDUDGZ 1335.0000 1110.0000 N R180 - 00
IO: inpB_1_0 PDUDGZ 1245.0000 1110.0000 N R180 - 00
IO: inpB_2_0 PDUDGZ 1155.0000 1110.0000 N R180 - 00
IO: inpB_3_0 PDUDGZ 1065.0000 1110.0000 N R180 - 00
IO: inpA_0_0 PDUDGZ 975.0000 1110.0000 N R180 - 00
IO: inpA_1_0 PDUDGZ 885.0000 1110.0000 N R180 - 00
IO: inpA_2_0 PDUDGZ 795.0000 1110.0000 N R180 - 00
IO: inpA_3_0 PDUDGZ 705.0000 1110.0000 N R180 - 00
IO: inpB_0 PDUDGZ 615.0000 1110.0000 N R180 - 00
IO: inpB_1 PDUDGZ 525.0000 1110.0000 N R180 - 00
IO: inpB_2 PDUDGZ 435.0000 1110.0000 N R180 - 00
IO: inpB_3 PDUDGZ 345.0000 1110.0000 N R180 - 00
IO: inpA_0 PDUDGZ 255.0000 1110.0000 N R180 - 00
IO: inpA_1 PDUDGZ 165.0000 1110.0000 N R180 - 00
IO: inpA_2 PDUDGZ 75.0000 1110.0000 N R180 - 00
IO: inpA_3 PDUDGZ -15.0000 1110.0000 N R180 - 00
IO: vdd1 PVDDDGZ -105.0000 1110.0000 N R180 - 00
IO: c1 PCORNER -405.0000 1110.0000 NW R270 - 00
IO: padClkG PDUDGZ -405.0000 660.0000 W R270 - 00
IO: c4 PCORNER -405.0000 0.0000 SW R0 - 00
IO: vss1 PVSSDGZ -105.0000 0.0000 S R0 - 00
IO: opRes_0_2 PDO12CDG -15.0000 0.0000 S R0 - 00
IO: opRes_1_2 PDO12CDG 75.0000 0.0000 S R0 - 00
IO: opRes_2_2 PDO12CDG 165.0000 0.0000 S R0 - 00
IO: opRes_3_2 PDO12CDG 255.0000 0.0000 S R0 - 00
IO: opRes_0_1 PDO12CDG 345.0000 0.0000 S R0 - 00
IO: opRes_1_1 PDO12CDG 435.0000 0.0000 S R0 - 00
IO: opRes_2_1 PDO12CDG 525.0000 0.0000 S R0 - 00
IO: opRes_3_1 PDO12CDG 615.0000 0.0000 S R0 - 00
IO: opRes_0_0 PDO12CDG 705.0000 0.0000 S R0 - 00
IO: opRes_1_0 PDO12CDG 795.0000 0.0000 S R0 - 00
IO: opRes_2_0 PDO12CDG 885.0000 0.0000 S R0 - 00
IO: opRes_3_0 PDO12CDG 975.0000 0.0000 S R0 - 00
IO: opRes_0 PDO12CDG 1065.0000 0.0000 S R0 - 00
IO: opRes_1 PDO12CDG 1155.0000 0.0000 S R0 - 00
IO: opRes_2 PDO12CDG 1245.0000 0.0000 S R0 - 00
IO: opRes_3 PDO12CDG 1335.0000 0.0000 S R0 - 00
IO: vdd2 PVDDDGZ 1425.0000 660.0000 E R90 - 00
IO: c3 PCORNER 1425.0000 0.0000 SE R90 - 00

##########################################################################
#  <IOPins>                                                              #
#    <Pin name="pin_name" type="clock|power|ground|analog"               #
#         status="covered|fixed|placed" is_special=1 >                   #
#      <Port>                                                            #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d />             #
#        <Via name="via_name" x=1 y=2 /> ...                             #
#        <Layer id=id spacing=1.2 drw=1.2>                               #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                           #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />          #
#        </Layer> ...                                                    #
#      </Port>  ...                                                      #
#      <Antenna model=num type="name" value=float_num layer=num /> ...   #
#    </Pin> ...                                                          #
#  </IOPins>                                                             #
##########################################################################


#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
